### ISSUE TITLE
Dulplication of `AfterFunctionDeclarationName`

### ISSUE THREAD

**Issue by tonyho** [alandefreitas/clang-unformat#17]
When I running the unformat, it would generate 2 line  with same content:

```
  AfterFunctionDeclarationName: false              # edit distance 69
  AfterFunctionDeclarationName: false              # edit distance 69
```

In the section of :

```
SpaceBeforeParensOptions:
  AfterControlStatements: false                    # edit distance 69
  AfterForeachMacros: true                         # did not affect the output
  AfterFunctionDeclarationName: false              # edit distance 69
  AfterFunctionDeclarationName: false              # edit distance 69
  AfterFunctionDefinitionName: true                # did not affect the output
  AfterIfMacros: true                              # did not affect the output
  AfterOverloadedOperator: true                    # did not affect the output
  AfterRequiresInClause: true                      # did not affect the output
  AfterRequiresInExpression: true                  # did not affect the output
  BeforeNonEmptyParentheses: false                 # edit distance 69

```
